#!/bin/bash
docker run --restart always -d --name svgtool -p 1337:1337 svgtool-img bash -c "cd /svg_extruder_plating_tool_thingy && ☾ server.☾"

# docker save svgtool-img -o svgtool_docker.tar
# docker load -i svgtool_docker.tar
